# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLocation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.LocationClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyLocation", llm_response=llm_response, mode="request")
        return typing.cast(types.LocationClassification, result)

    def ExtractStories(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Story"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStories", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.Story"], result)

    def FindPreciseAddress(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AddressResolution:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FindPreciseAddress", llm_response=llm_response, mode="request")
        return typing.cast(types.AddressResolution, result)

    def SummarizeCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClusterSummary:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCluster", llm_response=llm_response, mode="request")
        return typing.cast(types.ClusterSummary, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLocation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.LocationClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyLocation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.LocationClassification, result)

    def ExtractStories(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Story"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStories", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.Story"], result)

    def FindPreciseAddress(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AddressResolution:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FindPreciseAddress", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AddressResolution, result)

    def SummarizeCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClusterSummary:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCluster", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClusterSummary, result)

    