# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class Company(BaseModel):
    name: typing.Optional[str] = None
    relationship: typing.Optional[str] = None

class DateInfo(BaseModel):
    asserted_text: typing.Optional[str] = None
    parsed: typing.Optional[str] = None
    precision: typing.Optional[str] = None

class Location(BaseModel):
    place_name: typing.Optional[str] = None
    lat: typing.Optional[float] = None
    lon: typing.Optional[float] = None
    place_type: typing.Optional[str] = None
    geo_precision: typing.Optional[str] = None
    visitability: typing.Optional[str] = None
    note: typing.Optional[str] = None

class Media(BaseModel):
    asset_type: typing.Optional[str] = None
    uri: typing.Optional[str] = None
    credit: typing.Optional[str] = None
    license: typing.Optional[str] = None
    date: typing.Optional[str] = None

class Person(BaseModel):
    name: typing.Optional[str] = None
    role_at_time: typing.Optional[str] = None
    team: typing.Optional[str] = None
    affiliation: typing.Optional[str] = None

class Product(BaseModel):
    product_line: typing.Optional[str] = None
    model: typing.Optional[str] = None
    codename: typing.Optional[str] = None
    generation: typing.Optional[str] = None
    design_language: typing.Optional[str] = None

class Provenance(BaseModel):
    source_type: typing.Optional[str] = None
    citation: typing.Optional[str] = None
    isbn: typing.Optional[str] = None
    author: typing.Optional[str] = None
    pub_year: typing.Optional[int] = None
    quote_snippet: typing.Optional[str] = None

class Relationships(BaseModel):
    contradicts: typing.Optional[typing.List[str]] = None
    references: typing.Optional[typing.List[str]] = None
    precedes: typing.Optional[typing.List[str]] = None

class Story(BaseModel):
    story_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    dates: typing.Optional["DateInfo"] = None
    locations: typing.Optional[typing.List["Location"]] = None
    forward_locale: typing.Optional["Location"] = None
    people: typing.Optional[typing.List["Person"]] = None
    products: typing.Optional[typing.List["Product"]] = None
    companies: typing.Optional[typing.List["Company"]] = None
    event_type: typing.Optional[typing.List[str]] = None
    themes: typing.Optional[typing.List[str]] = None
    tone: typing.Optional[typing.List[str]] = None
    business_phase: typing.Optional[str] = None
    era: typing.Optional[str] = None
    relationships: typing.Optional["Relationships"] = None
    provenance: typing.Optional[typing.List["Provenance"]] = None
    confidence: typing.Optional[float] = None
    freeform_tags: typing.Optional[typing.List[str]] = None
    media: typing.Optional[typing.List["Media"]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
