# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ClassifyLocation(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LocationClassification:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ClassifyLocation(place_name=place_name,place_type=place_type,note=note,story_title=story_title,story_summary=story_summary,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyLocation", args={
                "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,
            })
            return typing.cast(types.LocationClassification, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractStories(self, chapter_text: str,book_context: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Story"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractStories(chapter_text=chapter_text,book_context=book_context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractStories", args={
                "chapter_text": chapter_text,"book_context": book_context,
            })
            return typing.cast(typing.List["types.Story"], result.cast_to(types, types, stream_types, False, __runtime__))
    def FindPreciseAddress(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,original_lat: typing.Optional[float] = None,original_lon: typing.Optional[float] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.AddressResolution:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.FindPreciseAddress(place_name=place_name,place_type=place_type,note=note,story_title=story_title,story_summary=story_summary,original_lat=original_lat,original_lon=original_lon,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="FindPreciseAddress", args={
                "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,"original_lat": original_lat,"original_lon": original_lon,
            })
            return typing.cast(types.AddressResolution, result.cast_to(types, types, stream_types, False, __runtime__))
    def SummarizeCluster(self, stories: typing.List[str],location_name: str,zoom_level: int,
        baml_options: BamlCallOptions = {},
    ) -> types.ClusterSummary:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.SummarizeCluster(stories=stories,location_name=location_name,zoom_level=zoom_level,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="SummarizeCluster", args={
                "stories": stories,"location_name": location_name,"zoom_level": zoom_level,
            })
            return typing.cast(types.ClusterSummary, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLocation(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.LocationClassification, types.LocationClassification]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyLocation", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,
        })
        return baml_py.BamlSyncStream[stream_types.LocationClassification, types.LocationClassification](
          result,
          lambda x: typing.cast(stream_types.LocationClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.LocationClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractStories(self, chapter_text: str,book_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.Story"], typing.List["types.Story"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractStories", args={
            "chapter_text": chapter_text,"book_context": book_context,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.Story"], typing.List["types.Story"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.Story"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.Story"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FindPreciseAddress(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,original_lat: typing.Optional[float] = None,original_lon: typing.Optional[float] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AddressResolution, types.AddressResolution]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="FindPreciseAddress", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,"original_lat": original_lat,"original_lon": original_lon,
        })
        return baml_py.BamlSyncStream[stream_types.AddressResolution, types.AddressResolution](
          result,
          lambda x: typing.cast(stream_types.AddressResolution, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AddressResolution, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def SummarizeCluster(self, stories: typing.List[str],location_name: str,zoom_level: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClusterSummary, types.ClusterSummary]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="SummarizeCluster", args={
            "stories": stories,"location_name": location_name,"zoom_level": zoom_level,
        })
        return baml_py.BamlSyncStream[stream_types.ClusterSummary, types.ClusterSummary](
          result,
          lambda x: typing.cast(stream_types.ClusterSummary, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClusterSummary, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLocation(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyLocation", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,
        }, mode="request")
        return result
    def ExtractStories(self, chapter_text: str,book_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStories", args={
            "chapter_text": chapter_text,"book_context": book_context,
        }, mode="request")
        return result
    def FindPreciseAddress(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,original_lat: typing.Optional[float] = None,original_lon: typing.Optional[float] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FindPreciseAddress", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,"original_lat": original_lat,"original_lon": original_lon,
        }, mode="request")
        return result
    def SummarizeCluster(self, stories: typing.List[str],location_name: str,zoom_level: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SummarizeCluster", args={
            "stories": stories,"location_name": location_name,"zoom_level": zoom_level,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyLocation(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyLocation", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,
        }, mode="stream")
        return result
    def ExtractStories(self, chapter_text: str,book_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStories", args={
            "chapter_text": chapter_text,"book_context": book_context,
        }, mode="stream")
        return result
    def FindPreciseAddress(self, place_name: str,place_type: typing.Optional[str],note: typing.Optional[str],story_title: str,story_summary: str,original_lat: typing.Optional[float] = None,original_lon: typing.Optional[float] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FindPreciseAddress", args={
            "place_name": place_name,"place_type": place_type,"note": note,"story_title": story_title,"story_summary": story_summary,"original_lat": original_lat,"original_lon": original_lon,
        }, mode="stream")
        return result
    def SummarizeCluster(self, stories: typing.List[str],location_name: str,zoom_level: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SummarizeCluster", args={
            "stories": stories,"location_name": location_name,"zoom_level": zoom_level,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))