# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AddressResolution": types.AddressResolution,
    "stream_types.AddressResolution": stream_types.AddressResolution,

    "types.Company": types.Company,
    "stream_types.Company": stream_types.Company,

    "types.DateInfo": types.DateInfo,
    "stream_types.DateInfo": stream_types.DateInfo,

    "types.Location": types.Location,
    "stream_types.Location": stream_types.Location,

    "types.Media": types.Media,
    "stream_types.Media": stream_types.Media,

    "types.Person": types.Person,
    "stream_types.Person": stream_types.Person,

    "types.Product": types.Product,
    "stream_types.Product": stream_types.Product,

    "types.Provenance": types.Provenance,
    "stream_types.Provenance": stream_types.Provenance,

    "types.Relationships": types.Relationships,
    "stream_types.Relationships": stream_types.Relationships,

    "types.Story": types.Story,
    "stream_types.Story": stream_types.Story,


}